#!/usr/bin/env bash

MANAGED_BEGIN='<!-- rulez-claudeset:managed-begin -->'
MANAGED_END='<!-- rulez-claudeset:managed-end -->'
LEGACY_GENERATED_MARKER='<!-- generated by rulez-claudeset; do not edit directly -->'

manual_content_after_managed_block() {
  local path="$1"
  awk -v marker="$MANAGED_END" '
    found { print }
    $0 == marker { found=1 }
  ' "$path"
}

codex_forecast_prompt() {
  local path="$1"
  awk '
    $0 == "```text" && armed { in_prompt=1; next }
    in_prompt && $0 == "```" { exit }
    in_prompt { print }
    $0 == "Use this prompt as the complete task for the single `spawn_agent` call:" { armed=1 }
  ' "$path"
}

claude_forecast_prompt() {
  local path="$1"
  awk '
    $0 == "## Agent Prompt" { in_prompt=1; next }
    in_prompt {
      if (seen) { print }
      else if ($0 == "") { seen=1 }
    }
  ' "$path"
}

test_setup_codex_creates_rulez_tools_symlink() {
  local temp_home skill_src skill_dst output
  temp_home="$(make_temp_home)"
  skill_src="$REPO_ROOT/adapters/codex/skills/rulez-tools"
  skill_dst="$temp_home/.codex/skills/rulez-tools"

  output="$(HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex")"

  assert_symlink_target "$skill_dst" "$skill_src" "setup-codex installs rulez-tools symlink"
  assert_contains "Installed Codex skill: rulez-tools" "$output" "setup-codex prints success message"
}

test_setup_codex_generates_global_agents_guidance() {
  local temp_home agents output
  temp_home="$(make_temp_home)"
  agents="$temp_home/.codex/AGENTS.md"

  output="$(HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex")"

  assert_file_exists "$agents" "setup-codex writes global AGENTS.md"
  assert_eq "$MANAGED_BEGIN" "$(sed -n '1p' "$agents")" "managed Rulez block is first"
  assert_eq "1" "$(grep -cFx "$MANAGED_BEGIN" "$agents")" "AGENTS.md has one managed begin marker"
  assert_eq "1" "$(grep -cFx "$MANAGED_END" "$agents")" "AGENTS.md has one managed end marker"
  assert_contains "Global rules applied to all projects via rulez-claudeset." "$(cat "$agents")" "AGENTS.md includes shared RULEZ.md"
  assert_contains "## Worktrees" "$(cat "$agents")" "AGENTS.md includes Codex worktree rules"
  assert_contains "Never create sibling worktrees" "$(cat "$agents")" "AGENTS.md rejects sibling worktrees"
  assert_contains "Updated Codex guidance block:" "$output" "setup-codex reports managed guidance update"
}

test_codex_keychain_guidance_is_codex_specific() {
  local temp_home agents shared_guidance codex_guidance
  temp_home="$(make_temp_home)"
  agents="$temp_home/.codex/AGENTS.md"
  shared_guidance="$(cat "$REPO_ROOT/RULEZ.md")"
  codex_guidance="$(cat "$REPO_ROOT/adapters/codex/AGENTS.append.md")"

  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null

  assert_contains "## GitHub CLI Authentication" "$codex_guidance" "Codex appendix includes Keychain guidance"
  assert_not_contains "sandbox cannot read the token from Keychain" "$shared_guidance" "shared RULEZ.md excludes Codex-only Keychain guidance"
  assert_contains "sandbox cannot read the token from Keychain" "$(cat "$agents")" "generated AGENTS.md includes Keychain guidance"
}

test_setup_codex_migrates_legacy_generated_agents_guidance() {
  local temp_home agents
  temp_home="$(make_temp_home)"
  agents="$temp_home/.codex/AGENTS.md"

  mkdir -p "$(dirname "$agents")"
  printf '%s\nstale generated guidance\n' "$LEGACY_GENERATED_MARKER" > "$agents"

  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null

  assert_eq "$MANAGED_BEGIN" "$(sed -n '1p' "$agents")" "legacy generated file migrates to managed block"
  assert_contains "Global rules applied to all projects via rulez-claudeset." "$(cat "$agents")" "legacy migration installs current guidance"
  assert_not_contains "$LEGACY_GENERATED_MARKER" "$(cat "$agents")" "legacy whole-file marker is removed"
  assert_not_contains "stale generated guidance" "$(cat "$agents")" "legacy stale content is removed"
}

test_setup_codex_prepends_managed_block_to_manual_agents_guidance() {
  local temp_home agents output manual actual_manual
  temp_home="$(make_temp_home)"
  agents="$temp_home/.codex/AGENTS.md"
  manual='<!-- context7 -->
Use Context7 MCP to fetch current documentation.
<!-- context7 -->'

  mkdir -p "$(dirname "$agents")"
  printf '%s\n' "$manual" > "$agents"

  output="$(HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex")"
  actual_manual="$(manual_content_after_managed_block "$agents")"

  assert_contains "Updated Codex guidance block:" "$output" "manual guidance setup succeeds"
  assert_eq "$MANAGED_BEGIN" "$(sed -n '1p' "$agents")" "Rulez block precedes manual guidance"
  assert_eq "$manual" "$actual_manual" "manual Context7 guidance is preserved byte-for-byte"

  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null

  assert_eq "1" "$(grep -cFx "$MANAGED_BEGIN" "$agents")" "rerun keeps one managed begin marker"
  assert_eq "1" "$(grep -cFx "$MANAGED_END" "$agents")" "rerun keeps one managed end marker"
  assert_eq "$manual" "$(manual_content_after_managed_block "$agents")" "rerun still preserves manual guidance"
}

test_setup_codex_refreshes_managed_block_and_preserves_outside_content() {
  local temp_home agents manual
  temp_home="$(make_temp_home)"
  agents="$temp_home/.codex/AGENTS.md"
  manual='# My Codex rules

Keep this exact text.'

  mkdir -p "$(dirname "$agents")"
  {
    printf '%s\n' "$MANAGED_BEGIN"
    printf 'stale managed guidance\n'
    printf '%s\n' "$MANAGED_END"
    printf '%s\n' "$manual"
  } > "$agents"

  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null

  assert_eq "$MANAGED_BEGIN" "$(sed -n '1p' "$agents")" "refreshed managed block remains first"
  assert_contains "Global rules applied to all projects via rulez-claudeset." "$(cat "$agents")" "managed block refreshes current guidance"
  assert_not_contains "stale managed guidance" "$(cat "$agents")" "stale managed guidance is removed"
  assert_eq "$manual" "$(manual_content_after_managed_block "$agents")" "outside manual content is preserved"
}

test_setup_codex_uses_gnu_stat_mode_probe_before_bsd_fallback() {
  local temp_home agents output status
  temp_home="$(make_temp_home)"
  agents="$temp_home/.codex/AGENTS.md"

  mkdir -p "$temp_home/bin" "$(dirname "$agents")"
  cat > "$temp_home/bin/stat" <<'EOF'
#!/bin/sh
case "$1" in
  -c)
    printf '664\n'
    ;;
  -f)
    printf 'GNU filesystem report, not a mode\n664\n'
    ;;
  *)
    exit 2
    ;;
esac
EOF
  chmod +x "$temp_home/bin/stat"
  printf '# Manual Codex rules\n' > "$agents"

  set +e
  output="$(PATH="$temp_home/bin:$PATH" HOME="$temp_home" CODEX_DIR="$temp_home/.codex" \
    bash "$REPO_ROOT/bin/setup-codex" 2>&1)"
  status=$?
  set +e

  assert_eq "0" "$status" "GNU stat mode probe completes setup-codex"
  assert_not_contains "invalid mode" "$output" "GNU stat output never reaches chmod"
  assert_eq "# Manual Codex rules" "$(manual_content_after_managed_block "$agents")" \
    "GNU stat path preserves manual guidance"
}

test_setup_codex_rejects_malformed_managed_markers_before_side_effects() {
  local case_name temp_home agents skill_dst content before output status

  for case_name in begin-only end-only reversed duplicate-begin duplicate-end; do
    temp_home="$(make_temp_home)"
    agents="$temp_home/.codex/AGENTS.md"
    skill_dst="$temp_home/.codex/skills/rulez-tools"
    mkdir -p "$(dirname "$agents")"

    case "$case_name" in
      begin-only)
        content="$MANAGED_BEGIN
stale" ;;
      end-only)
        content="stale
$MANAGED_END" ;;
      reversed)
        content="$MANAGED_END
stale
$MANAGED_BEGIN" ;;
      duplicate-begin)
        content="$MANAGED_BEGIN
$MANAGED_BEGIN
stale
$MANAGED_END" ;;
      duplicate-end)
        content="$MANAGED_BEGIN
stale
$MANAGED_END
$MANAGED_END" ;;
    esac
    printf '%s\n' "$content" > "$agents"
    before="$(cat "$agents")"

    set +e
    output="$(HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" 2>&1)"
    status=$?
    set +e

    assert_eq "1" "$status" "$case_name markers halt setup-codex"
    assert_contains "malformed Rulez managed guidance markers" "$output" "$case_name markers explain corruption"
    assert_eq "$before" "$(cat "$agents")" "$case_name markers leave AGENTS.md unchanged"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [ ! -e "$skill_dst" ] && [ ! -L "$skill_dst" ]; then
      printf '  ok: %s\n' "$case_name markers leave skill link untouched"
    else
      TESTS_FAILED=$((TESTS_FAILED + 1))
      printf '  FAIL: %s\n' "$case_name markers leave skill link untouched"
    fi
  done
}

test_setup_codex_is_idempotent_for_existing_symlink() {
  local temp_home skill_src skill_dst
  temp_home="$(make_temp_home)"
  skill_src="$REPO_ROOT/adapters/codex/skills/rulez-tools"
  skill_dst="$temp_home/.codex/skills/rulez-tools"

  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null
  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null

  assert_symlink_target "$skill_dst" "$skill_src" "setup-codex can be re-run"
}

test_setup_codex_replaces_broken_symlink() {
  local temp_home skill_src skill_dst
  temp_home="$(make_temp_home)"
  skill_src="$REPO_ROOT/adapters/codex/skills/rulez-tools"
  skill_dst="$temp_home/.codex/skills/rulez-tools"

  mkdir -p "$temp_home/.codex/skills"
  ln -s "$temp_home/missing-target" "$skill_dst"

  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null

  assert_symlink_target "$skill_dst" "$skill_src" "setup-codex replaces broken symlink"
}

test_setup_codex_refuses_to_overwrite_real_directory() {
  local temp_home skill_dst output status
  temp_home="$(make_temp_home)"
  skill_dst="$temp_home/.codex/skills/rulez-tools"

  mkdir -p "$skill_dst"

  set +e
  output="$(HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" 2>&1)"
  status=$?
  set +e

  assert_eq "1" "$status" "setup-codex fails when destination is a real directory"
  assert_contains "Refusing to overwrite non-symlink" "$output" "setup-codex explains real-directory collision"
}

test_setup_codex_refuses_to_overwrite_real_file() {
  local temp_home skill_dst output status
  temp_home="$(make_temp_home)"
  skill_dst="$temp_home/.codex/skills/rulez-tools"

  mkdir -p "$(dirname "$skill_dst")"
  printf 'local file\n' > "$skill_dst"

  set +e
  output="$(HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" 2>&1)"
  status=$?
  set +e

  assert_eq "1" "$status" "setup-codex fails when destination is a real file"
  assert_contains "Refusing to overwrite non-symlink" "$output" "setup-codex explains real-file collision"
}

test_rulez_tools_skill_frontmatter_is_valid() {
  local skill_file
  skill_file="$REPO_ROOT/adapters/codex/skills/rulez-tools/SKILL.md"

  assert_eq "---" "$(sed -n '1p' "$skill_file")" "skill frontmatter opens"
  assert_eq "name: rulez-tools" "$(sed -n '2p' "$skill_file")" "skill name is rulez-tools"
  assert_contains 'description: "Use for Rulez shared tooling in Codex:' "$(sed -n '3p' "$skill_file")" "skill description is quoted YAML"
  assert_eq "---" "$(sed -n '4p' "$skill_file")" "skill frontmatter closes"
}

test_rulez_tools_skill_documents_punts_workflows() {
  local skill_file skill_body
  skill_file="$REPO_ROOT/adapters/codex/skills/rulez-tools/SKILL.md"
  skill_body="$(cat "$skill_file")"

  assert_contains "use rulez-tools to enrich punts" "$skill_body" "skill documents punts enrich phrasing"
  assert_contains "use rulez-tools to triage punts" "$skill_body" "skill documents punts triage phrasing"
  assert_contains ".claude/punts/raw" "$skill_body" "skill documents shared raw punts storage"
  assert_contains ".claude/punts/state/slice-" "$skill_body" "skill documents punt slice storage"
  assert_contains "spawn_agent" "$skill_body" "skill documents Codex subagent enrichment"
  assert_contains "APPROVE / REJECT / SKIP / MERGE" "$skill_body" "skill documents interactive triage choices"
  assert_contains "scripts/punts-extract-prompt.sh" "$skill_body" "skill documents shared prompt builder"
}

test_rulez_tools_skill_documents_cycle_goal_workflow() {
  local skill_file skill_body skill_description
  skill_file="$REPO_ROOT/adapters/codex/skills/rulez-tools/SKILL.md"
  skill_body="$(cat "$skill_file")"
  skill_description="$(sed -n '3p' "$skill_file")"

  assert_contains "cycle goal watchers" "$skill_description" "skill description advertises cycle goal watchers"
  assert_contains "launching a cycle watcher" "$skill_body" "skill trigger list includes cycle watchers"
  assert_contains 'use rulez-tools to cycle <reviewer|fixer> <spec|plan|PR> <target(s)>' "$skill_body" "skill documents Codex cycle syntax"
  assert_not_contains 'use rulez-tools to cycle <reviewer|fixer> <loop|goal>' "$skill_body" "Codex cycle syntax omits mode"
  assert_contains 'Call `get_goal` before running the builder.' "$skill_body" "cycle preflights task goal"
  assert_contains 'status other than no goal or `complete`' "$skill_body" "cycle refuses unfinished goals"
  assert_contains 'cycle-prompt.sh" <role> goal <type> <target...>' "$skill_body" "cycle delegates with literal goal mode"
  assert_contains 'show its stderr unchanged' "$skill_body" "cycle preserves builder validation errors"
  assert_contains '4,000-character' "$skill_body" "cycle enforces Codex objective limit"
  assert_contains 'Call `create_goal` once' "$skill_body" "cycle launches one persisted goal"
  assert_contains 'Do not use `update_goal`' "$skill_body" "cycle never mutates existing goal state"
}

test_rulez_tools_skill_documents_standalone_forecast_workflow() {
  local skill_file skill_body skill_description
  skill_file="$REPO_ROOT/adapters/codex/skills/rulez-tools/SKILL.md"
  skill_body="$(cat "$skill_file")"
  skill_description="$(sed -n '3p' "$skill_file")"

  assert_contains "standalone spec2pr forecasting" "$skill_description" "skill description advertises standalone forecasting"
  assert_contains "standalone spec2pr forecasting" "$skill_body" "skill trigger prose advertises standalone forecasting"
  assert_contains 'use rulez-tools to forecast <path>' "$skill_body" "skill documents forecast invocation"
  assert_contains 'Call `spawn_agent` exactly once' "$skill_body" "forecast launches one subagent"
  assert_contains 'fork_context: false' "$skill_body" "forecast uses fresh non-forked context semantics"
  assert_not_contains 'fork_turns' "$skill_body" "forecast avoids obsolete spawn_agent arguments"
  assert_contains 'Read <path> and relevant context in <repository-root>.' "$skill_body" "forecast prompt reads artifact and repository context"
  assert_contains '131072' "$skill_body" "forecast prompt includes byte threshold"
  assert_contains 'Risk: LOW, MEDIUM, or HIGH' "$skill_body" "forecast prompt includes risk labels"
  assert_contains 'Expected size: a rough changed-LOC range' "$skill_body" "forecast prompt includes rough size"
  assert_contains 'Reasons:' "$skill_body" "forecast prompt includes reasons"
  assert_contains 'Suggested split:' "$skill_body" "forecast prompt includes conditional split advice"
  assert_contains 'modify anything and do not launch another agent' "$skill_body" "forecast prompt is read-only and non-nested"
  assert_contains "return the subagent's forecast without re-estimating" "$skill_body" "forecast returns subagent result directly"
  assert_contains 'no retry, reviewer, implementation agent, or split agent' "$skill_body" "forecast authorizes one forecast agent only"
  assert_contains 'Do not run external `claude`, external `codex`, `spec2pr`, or `spec2pr-split`' "$skill_body" "forecast forbids external dispatch"
  assert_eq "$(claude_forecast_prompt "$REPO_ROOT/commands/rulez/spec2pr-forecast.md")" "$(codex_forecast_prompt "$skill_file")" "Codex forecast prompt matches Claude command prompt"
}

test_rulez_tools_skill_avoids_forecast_extra_machinery() {
  local skill_file skill_body
  skill_file="$REPO_ROOT/adapters/codex/skills/rulez-tools/SKILL.md"
  skill_body="$(cat "$skill_file")"

  assert_not_contains "shared helper" "$skill_body" "forecast has no shared helper"
  assert_not_contains "JSON schema" "$skill_body" "forecast has no JSON schema"
  assert_not_contains "cache" "$skill_body" "forecast has no cache"
  assert_not_contains "state manifest" "$skill_body" "forecast has no state manifest"
  assert_not_contains "exact byte arithmetic" "$skill_body" "forecast has no exact arithmetic"
  assert_not_contains "SPEC2PR OK/WARN/SPLIT/HALT" "$skill_body" "forecast has no status tokens"
}

test_readme_documents_codex_cycle_goal_workflow() {
  local readme
  readme="$(cat "$REPO_ROOT/README.md")"

  assert_contains "use rulez-tools to cycle reviewer spec docs/superpowers/specs/foo-design.md" "$readme" "README shows Codex reviewer cycle invocation"
  assert_contains "use rulez-tools to cycle fixer PR 34" "$readme" "README shows Codex fixer cycle invocation"
  assert_contains 'Codex cycle syntax omits the Claude `mode` selector' "$readme" "README documents implicit goal mode"
  assert_contains "Reviewer and fixer watchers run in separate Codex tasks." "$readme" "README documents one watcher per task"
  assert_contains "cycle goal watchers" "$readme" "README capability list includes cycle watchers"
}

test_readme_documents_standalone_spec2pr_forecast() {
  local readme
  readme="$(cat "$REPO_ROOT/README.md")"

  assert_contains "use rulez-tools to forecast docs/superpowers/specs/foo-design.md" "$readme" "README shows Codex forecast invocation"
  assert_contains "/rulez:spec2pr-forecast docs/superpowers/plans/foo-design-plan.md" "$readme" "README shows Claude forecast invocation"
  assert_contains "/rulez:spec2pr-forecast <path>" "$readme" "README command table includes forecast command"
  assert_contains "lightweight standalone forecast before running spec2pr" "$readme" "README explains forecast timing"
  assert_contains "one native subagent from the current tool, using that" "$readme" "README documents one native subagent"
  assert_contains "tool's default model and quota" "$readme" "README documents default model and quota"
  assert_contains "LOW" "$readme" "README documents LOW forecast risk"
  assert_contains "MEDIUM" "$readme" "README documents MEDIUM forecast risk"
  assert_contains "HIGH" "$readme" "README documents HIGH forecast risk"
  assert_contains "131072" "$readme" "README documents PR diff threshold"
  assert_contains "rough changed-LOC range" "$readme" "README documents rough changed-LOC range"
  assert_contains "Reasons" "$readme" "README documents forecast reasons"
  assert_contains '`Suggested split` is omitted for `LOW` and included only for' "$readme" "README documents LOW split omission"
  assert_contains '`MEDIUM` or `HIGH`.' "$readme" "README documents MEDIUM/HIGH split inclusion"
  assert_contains "read-only" "$readme" "README documents read-only forecast"
  assert_contains "does not run spec2pr" "$readme" "README says forecast does not run spec2pr"
  assert_contains "does not create split files" "$readme" "README says forecast does not create split files"
  assert_contains "does not cache results" "$readme" "README says forecast does not cache results"
  assert_contains "does not emit exact byte or exit-code contracts" "$readme" "README avoids exact byte and exit-code contracts"
  assert_contains 'automatic forecast inside `spec2pr.sh` remains unchanged' "$readme" "README distinguishes existing pipeline forecast"
  assert_contains "standalone spec2pr forecasting" "$readme" "README capability list includes standalone forecasting"
}
