#!/usr/bin/env bash

MANAGED_BEGIN='<!-- rulez-claudeset:managed-begin -->'
MANAGED_END='<!-- rulez-claudeset:managed-end -->'
LEGACY_GENERATED_MARKER='<!-- generated by rulez-claudeset; do not edit directly -->'

manual_content_after_managed_block() {
  local path="$1"
  awk -v marker="$MANAGED_END" '
    found { print }
    $0 == marker { found=1 }
  ' "$path"
}

test_setup_codex_creates_rulez_tools_symlink() {
  local temp_home skill_src skill_dst output
  temp_home="$(make_temp_home)"
  skill_src="$REPO_ROOT/adapters/codex/skills/rulez-tools"
  skill_dst="$temp_home/.codex/skills/rulez-tools"

  output="$(HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex")"

  assert_symlink_target "$skill_dst" "$skill_src" "setup-codex installs rulez-tools symlink"
  assert_contains "Installed Codex skill: rulez-tools" "$output" "setup-codex prints success message"
}

test_setup_codex_generates_global_agents_guidance() {
  local temp_home agents output
  temp_home="$(make_temp_home)"
  agents="$temp_home/.codex/AGENTS.md"

  output="$(HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex")"

  assert_file_exists "$agents" "setup-codex writes global AGENTS.md"
  assert_eq "$MANAGED_BEGIN" "$(sed -n '1p' "$agents")" "managed Rulez block is first"
  assert_eq "1" "$(grep -cFx "$MANAGED_BEGIN" "$agents")" "AGENTS.md has one managed begin marker"
  assert_eq "1" "$(grep -cFx "$MANAGED_END" "$agents")" "AGENTS.md has one managed end marker"
  assert_contains "Global rules applied to all projects via rulez-claudeset." "$(cat "$agents")" "AGENTS.md includes shared RULEZ.md"
  assert_contains "## Worktrees" "$(cat "$agents")" "AGENTS.md includes Codex worktree rules"
  assert_contains "Never create sibling worktrees" "$(cat "$agents")" "AGENTS.md rejects sibling worktrees"
  assert_contains "Updated Codex guidance block:" "$output" "setup-codex reports managed guidance update"
}

test_setup_codex_migrates_legacy_generated_agents_guidance() {
  local temp_home agents
  temp_home="$(make_temp_home)"
  agents="$temp_home/.codex/AGENTS.md"

  mkdir -p "$(dirname "$agents")"
  printf '%s\nstale generated guidance\n' "$LEGACY_GENERATED_MARKER" > "$agents"

  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null

  assert_eq "$MANAGED_BEGIN" "$(sed -n '1p' "$agents")" "legacy generated file migrates to managed block"
  assert_contains "Global rules applied to all projects via rulez-claudeset." "$(cat "$agents")" "legacy migration installs current guidance"
  assert_not_contains "$LEGACY_GENERATED_MARKER" "$(cat "$agents")" "legacy whole-file marker is removed"
  assert_not_contains "stale generated guidance" "$(cat "$agents")" "legacy stale content is removed"
}

test_setup_codex_prepends_managed_block_to_manual_agents_guidance() {
  local temp_home agents output manual actual_manual
  temp_home="$(make_temp_home)"
  agents="$temp_home/.codex/AGENTS.md"
  manual='<!-- context7 -->
Use Context7 MCP to fetch current documentation.
<!-- context7 -->'

  mkdir -p "$(dirname "$agents")"
  printf '%s\n' "$manual" > "$agents"

  output="$(HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex")"
  actual_manual="$(manual_content_after_managed_block "$agents")"

  assert_contains "Updated Codex guidance block:" "$output" "manual guidance setup succeeds"
  assert_eq "$MANAGED_BEGIN" "$(sed -n '1p' "$agents")" "Rulez block precedes manual guidance"
  assert_eq "$manual" "$actual_manual" "manual Context7 guidance is preserved byte-for-byte"

  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null

  assert_eq "1" "$(grep -cFx "$MANAGED_BEGIN" "$agents")" "rerun keeps one managed begin marker"
  assert_eq "1" "$(grep -cFx "$MANAGED_END" "$agents")" "rerun keeps one managed end marker"
  assert_eq "$manual" "$(manual_content_after_managed_block "$agents")" "rerun still preserves manual guidance"
}

test_setup_codex_refreshes_managed_block_and_preserves_outside_content() {
  local temp_home agents manual
  temp_home="$(make_temp_home)"
  agents="$temp_home/.codex/AGENTS.md"
  manual='# My Codex rules

Keep this exact text.'

  mkdir -p "$(dirname "$agents")"
  {
    printf '%s\n' "$MANAGED_BEGIN"
    printf 'stale managed guidance\n'
    printf '%s\n' "$MANAGED_END"
    printf '%s\n' "$manual"
  } > "$agents"

  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null

  assert_eq "$MANAGED_BEGIN" "$(sed -n '1p' "$agents")" "refreshed managed block remains first"
  assert_contains "Global rules applied to all projects via rulez-claudeset." "$(cat "$agents")" "managed block refreshes current guidance"
  assert_not_contains "stale managed guidance" "$(cat "$agents")" "stale managed guidance is removed"
  assert_eq "$manual" "$(manual_content_after_managed_block "$agents")" "outside manual content is preserved"
}

test_setup_codex_rejects_malformed_managed_markers_before_side_effects() {
  local case_name temp_home agents skill_dst content before output status

  for case_name in begin-only end-only reversed duplicate-begin duplicate-end; do
    temp_home="$(make_temp_home)"
    agents="$temp_home/.codex/AGENTS.md"
    skill_dst="$temp_home/.codex/skills/rulez-tools"
    mkdir -p "$(dirname "$agents")"

    case "$case_name" in
      begin-only)
        content="$MANAGED_BEGIN
stale" ;;
      end-only)
        content="stale
$MANAGED_END" ;;
      reversed)
        content="$MANAGED_END
stale
$MANAGED_BEGIN" ;;
      duplicate-begin)
        content="$MANAGED_BEGIN
$MANAGED_BEGIN
stale
$MANAGED_END" ;;
      duplicate-end)
        content="$MANAGED_BEGIN
stale
$MANAGED_END
$MANAGED_END" ;;
    esac
    printf '%s\n' "$content" > "$agents"
    before="$(cat "$agents")"

    set +e
    output="$(HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" 2>&1)"
    status=$?
    set +e

    assert_eq "1" "$status" "$case_name markers halt setup-codex"
    assert_contains "malformed Rulez managed guidance markers" "$output" "$case_name markers explain corruption"
    assert_eq "$before" "$(cat "$agents")" "$case_name markers leave AGENTS.md unchanged"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [ ! -e "$skill_dst" ] && [ ! -L "$skill_dst" ]; then
      printf '  ok: %s\n' "$case_name markers leave skill link untouched"
    else
      TESTS_FAILED=$((TESTS_FAILED + 1))
      printf '  FAIL: %s\n' "$case_name markers leave skill link untouched"
    fi
  done
}

test_setup_codex_is_idempotent_for_existing_symlink() {
  local temp_home skill_src skill_dst
  temp_home="$(make_temp_home)"
  skill_src="$REPO_ROOT/adapters/codex/skills/rulez-tools"
  skill_dst="$temp_home/.codex/skills/rulez-tools"

  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null
  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null

  assert_symlink_target "$skill_dst" "$skill_src" "setup-codex can be re-run"
}

test_setup_codex_replaces_broken_symlink() {
  local temp_home skill_src skill_dst
  temp_home="$(make_temp_home)"
  skill_src="$REPO_ROOT/adapters/codex/skills/rulez-tools"
  skill_dst="$temp_home/.codex/skills/rulez-tools"

  mkdir -p "$temp_home/.codex/skills"
  ln -s "$temp_home/missing-target" "$skill_dst"

  HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" >/dev/null

  assert_symlink_target "$skill_dst" "$skill_src" "setup-codex replaces broken symlink"
}

test_setup_codex_refuses_to_overwrite_real_directory() {
  local temp_home skill_dst output status
  temp_home="$(make_temp_home)"
  skill_dst="$temp_home/.codex/skills/rulez-tools"

  mkdir -p "$skill_dst"

  set +e
  output="$(HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" 2>&1)"
  status=$?
  set +e

  assert_eq "1" "$status" "setup-codex fails when destination is a real directory"
  assert_contains "Refusing to overwrite non-symlink" "$output" "setup-codex explains real-directory collision"
}

test_setup_codex_refuses_to_overwrite_real_file() {
  local temp_home skill_dst output status
  temp_home="$(make_temp_home)"
  skill_dst="$temp_home/.codex/skills/rulez-tools"

  mkdir -p "$(dirname "$skill_dst")"
  printf 'local file\n' > "$skill_dst"

  set +e
  output="$(HOME="$temp_home" CODEX_DIR="$temp_home/.codex" bash "$REPO_ROOT/bin/setup-codex" 2>&1)"
  status=$?
  set +e

  assert_eq "1" "$status" "setup-codex fails when destination is a real file"
  assert_contains "Refusing to overwrite non-symlink" "$output" "setup-codex explains real-file collision"
}

test_rulez_tools_skill_frontmatter_is_valid() {
  local skill_file
  skill_file="$REPO_ROOT/adapters/codex/skills/rulez-tools/SKILL.md"

  assert_eq "---" "$(sed -n '1p' "$skill_file")" "skill frontmatter opens"
  assert_eq "name: rulez-tools" "$(sed -n '2p' "$skill_file")" "skill name is rulez-tools"
  assert_contains 'description: "Use for Rulez shared tooling in Codex:' "$(sed -n '3p' "$skill_file")" "skill description is quoted YAML"
  assert_eq "---" "$(sed -n '4p' "$skill_file")" "skill frontmatter closes"
}

test_rulez_tools_skill_documents_punts_workflows() {
  local skill_file skill_body
  skill_file="$REPO_ROOT/adapters/codex/skills/rulez-tools/SKILL.md"
  skill_body="$(cat "$skill_file")"

  assert_contains "use rulez-tools to enrich punts" "$skill_body" "skill documents punts enrich phrasing"
  assert_contains "use rulez-tools to triage punts" "$skill_body" "skill documents punts triage phrasing"
  assert_contains ".claude/punts/raw" "$skill_body" "skill documents shared raw punts storage"
  assert_contains ".claude/punts/state/slice-" "$skill_body" "skill documents punt slice storage"
  assert_contains "spawn_agent" "$skill_body" "skill documents Codex subagent enrichment"
  assert_contains "APPROVE / REJECT / SKIP / MERGE" "$skill_body" "skill documents interactive triage choices"
  assert_contains "scripts/punts-extract-prompt.sh" "$skill_body" "skill documents shared prompt builder"
}
